os:
  - linux

sudo: false

addons:
  apt:
    packages:
    - libgmp-dev
    - libmpfr-dev
    - libmpc-dev
    - cvs
    - texinfo
    - lzip

compiler:
  - gcc

script:
  - 'make download && make m68000-skip-native'
