language: c

os:
  - linux

sudo: false

addons:
  apt:
    packages:
    - libgmp-dev
    - libmpfr-dev
    - libmpc-dev
    - cvs
    - texinfo
    - lzip

compiler:
  - gcc

env:
  matrix:
    - TARGET_CPU=m68000
    - TARGET_CPU=m68020-60
    - TARGET_CPU=5475

script:
  - 'make download && make ${TARGET_CPU}-skip-native OUT="> /dev/null"'
