language: c

os:
  - osx
  - linux

sudo: false

addons:
  apt:
    packages:
    - libgmp-dev
    - libmpfr-dev
    - libmpc-dev
    - cvs
    - texinfo
    - lzip

compiler:
  - gcc

env:
  matrix:
    - TARGET_CPU=m68000
    - TARGET_CPU=m68020-60
    - TARGET_CPU=5475

before_install:
  - 'if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update > /dev/null && brew install libmpc ; fi'
  - 'if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install cvs ; fi'
  - 'if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$CC" == "gcc" ] ; then CC=gcc-4.9; fi'

script:
  - 'make download'
  - 'make ${TARGET_CPU}-skip-native OUT="> /dev/null"'
